### ISSUE TITLE
Ambari Content-Type is incorrect for blueprint add.

### ISSUE THREAD

**Issue by dmtucker** [dmtucker/yaas#17]
https://github.com/dmtucker/yaas/blob/master/yaas/blueprint.py#L53

``` python
        response = requests.post(
            config.href(
                '/api/v1/blueprints/{name}'.format(
                    name=blueprint['Blueprints']['blueprint_name'])),
            data=json.dumps(blueprint),  # `json=blueprint` would be better, but it doesn't work!
            params={'validate_topology': subargs.validate_topology},
            **config.requests_opts())
```

`json=blueprint` causes `requests` to use `Content-Type: application/json` which does not work correctly:

https://issues.apache.org/jira/browse/AMBARI-9016

**Comment by karth295** [comment]
I don't think this should be an issue against `yaas`. Presumably they won't deprecate this behavior in `v1` of the ambari api, because it breaks backwards compatibility.

**Comment by dmtucker** [comment]
Well, it's not a bug that's forsure, but I think we should be tracking this somehow...
