### ISSUE TITLE
Allow custom names when uploading

### ISSUE THREAD

**Issue by dmtucker** [dmtucker/yaas#21]
```
$ yaas blueprint add foo.json
$ yaas blueprint list
blueprint_name-in-foo
$ yaas blueprint add foo.json --name=bar
$ yaas blueprint list
blueprint_name-in-foo
bar
```

**Comment by karth295** [comment]
You can't add a blueprint without a name (I changed that). Blueprints aren't supposed to have names inside them--I feel like that is something you added to scripts before we had `yaas`

**Comment by dmtucker** [comment]
Woah, you're right!
From https://cwiki.apache.org/confluence/display/AMBARI/Blueprints,

> blueprint_name : Optional field which specifies that name of the blueprint.  Typically the name of the blueprint is specified in the URL of the REST invocation.  The only reason to specify the name in the blueprint is when creating multiple blueprints via a single REST invocation.

I didn't add it to any scripts, but I always included it because the example blueprints I modeled ours after always had it.
