### ISSUE TITLE
Blueprint show should not display `content` fields

### ISSUE THREAD

**Issue by karth295** [dmtucker/yaas#32]
Ambari blueprint of a concrete cluster includes the contents of *.xml files when you get them from `/api/v1/clusters/foo?format=blueprint`. However, the same blueprint cannot be posted back to the server to create a new cluster. Yaas should strip the content fields unless `--raw` is specified.

**Comment by dmtucker** [comment]
Is this really something YAAS should do long-term, or is it a bug that Ambari doesn't accept these fields? It seems to me that the issue of not being able to upload a blueprint Ambari created back to Ambari is the latter...
